### PR TITLE
PORTAL-5234 Revert update-notifier to no-esm version in vputil and lgputil

### PR DESCRIPTION
**Pull request by markkong318**
Removed `update-notifier`
~~Node 12 has some problem to process esm package, so revert it to cjs version of update-notifier~~

### CODE REVIEW

**Review by toruta39 — CHANGES_REQUESTED** [review]
the older v5 package has vulnerability alert, it's better to switch to esm than rollback to cjs

**Comment by markkong318** [comment]
> the older v5 package has vulnerability alert, it's better to switch to esm than rollback to cjs
@toruta39 

Because error message only on Node v12
I think we could suppress the error message by adding `catch`

import('update-notifier').then(updateNotifier => {
  updateNotifier.default({ pkg: packageJson }).notify();
}).catch(() => {});

It is not a main feature in our app so ignore will have no effect I think

**Comment by toruta39** [comment]
Comparing to mute the error, it's better to just uninstall the package and drop the feature for now (until have time to support esm).

**Comment by markkong318** [comment]
Removed `update-notifier`

**Review by toruta39 — APPROVED** [review]
LGTM

**Pull request merged**
